# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-28 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='machine',
            name='operatingSystem',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
