# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-28 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180528_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='dNSHostName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='machine',
            name='distinguishedName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='machine',
            name='operatingSystemServicePack',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
