# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-28 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180528_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='machine',
            name='dNSHostName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='machine',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='machine',
            name='distinguishedName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='machine',
            name='operatingSystem',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='machine',
            name='operatingSystemServicePack',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
