# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-28 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180528_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='svr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn', models.CharField(blank=True, max_length=50)),
                ('operatingSystem', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('operatingSystemServicePack', models.CharField(blank=True, max_length=255)),
                ('distinguishedName', models.CharField(blank=True, max_length=255)),
                ('dNSHostName', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
