# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-03 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20180528_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='operatingSystem',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='svr',
            name='operatingSystem',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
