# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-03 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20180603_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='pcuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.user'),
        ),
    ]
