# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-03 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_machine_pcuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='pcuser',
            new_name='user',
        ),
    ]
