# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-04 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20180603_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='windowsLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255)),
                ('available', models.IntegerField(blank=True)),
                ('inUse', models.IntegerField(blank=True)),
                ('free', models.IntegerField(blank=True)),
                ('osName', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='windowsLicense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.windowsLicense'),
        ),
    ]
