# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-05 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20180604_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.user'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='windowsLicense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.windowsLicense'),
        ),
    ]
