# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-05 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20180605_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowssvrlicense',
            name='available',
            field=models.IntegerField(default=0),
        ),
    ]
