# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-05 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20180605_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowslicense',
            name='available',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='windowslicense',
            name='free',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='windowslicense',
            name='inUse',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='windowssvrlicense',
            name='free',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='windowssvrlicense',
            name='inUse',
            field=models.IntegerField(default=0),
        ),
    ]
