# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-12 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20180605_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='OU',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
