# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-14 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_svr_ou'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='aktualizacja',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
