# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-14 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_machine_aktualizacja'),
    ]

    operations = [
        migrations.CreateModel(
            name='officeLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255)),
                ('available', models.IntegerField(default=0)),
                ('inUse', models.IntegerField(default=0)),
                ('free', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
