# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-14 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_officelicense'),
    ]

    operations = [
        migrations.AddField(
            model_name='officelicense',
            name='vol',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
