# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-14 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_officelicense_vol'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='officeLicense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.officeLicense'),
        ),
    ]
