# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-15 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_machine_officelicense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officelicense',
            name='available',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='officelicense',
            name='free',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='officelicense',
            name='inUse',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
