# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-06 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20180615_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='rodo',
            field=models.BooleanField(default=True),
        ),
    ]
