# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-06 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_machine_rodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='rodo',
            field=models.CharField(blank=True, default='True', max_length=255),
        ),
    ]
