# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-06 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_auto_20180706_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='rodo',
            field=models.BooleanField(default=True),
        ),
    ]
