# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-15 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_auto_20180815_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='dep',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
