# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-15 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_auto_20180815_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='mac',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
