# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-11 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_auto_20180815_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='SamAccountName',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
