# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-04 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_termshift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termshift',
            old_name='dateIn',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='termshift',
            name='dateOut',
        ),
    ]
