# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-04 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_auto_20181004_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='termshift',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='termshift',
            name='typ',
            field=models.IntegerField(choices=[(1, 'Przyjęcie'), (2, 'Wydanie'), (3, 'Wyslany do naprawy'), (4, 'Przyjecie z naprawy'), (5, 'Utylizacja')], default=None),
        ),
    ]
