# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-08 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_auto_20181004_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termshift',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
