# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-09 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_auto_20181008_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termshift',
            name='eventDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
