# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-09 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_auto_20181009_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termshift',
            name='eventDate',
        ),
    ]
