# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-09 07:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_termshift_eventdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termshift',
            name='eventDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 9, 9, 33, 1, 229037), null=True),
        ),
    ]
