# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-18 12:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_auto_20181011_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='foamFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.FilePathField()),
            ],
        ),
        migrations.AlterField(
            model_name='termshift',
            name='eventDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 18, 14, 42, 57, 798355), null=True),
        ),
    ]
