# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-18 17:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0048_auto_20181018_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foamfile',
            name='fileName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='termshift',
            name='eventDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 18, 19, 31, 35, 645848), null=True),
        ),
    ]
