# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-19 06:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_auto_20181018_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='foamRows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(blank=True, max_length=4, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('workCenter', models.CharField(blank=True, max_length=10, null=True)),
                ('tura', models.CharField(blank=True, max_length=10, null=True)),
                ('ta', models.CharField(blank=True, max_length=10, null=True)),
                ('kol6', models.CharField(blank=True, max_length=10, null=True)),
                ('kol7', models.CharField(blank=True, max_length=10, null=True)),
                ('OrderNo', models.CharField(blank=True, max_length=20, null=True)),
                ('kol9', models.CharField(blank=True, max_length=20, null=True)),
                ('IndexSap', models.CharField(blank=True, max_length=20, null=True)),
                ('IndexSapNazwa', models.CharField(blank=True, max_length=20, null=True)),
                ('kol12', models.CharField(blank=True, max_length=20, null=True)),
                ('kol13', models.CharField(blank=True, max_length=20, null=True)),
                ('kol14', models.CharField(blank=True, max_length=20, null=True)),
                ('kol15', models.CharField(blank=True, max_length=20, null=True)),
                ('kol16', models.CharField(blank=True, max_length=20, null=True)),
                ('foamFile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.foamFile')),
            ],
        ),
        migrations.AlterField(
            model_name='termshift',
            name='eventDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 19, 8, 30, 0, 932016), null=True),
        ),
    ]
