# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-22 11:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_auto_20181019_0830'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='foamRows',
            new_name='foamRow',
        ),
        migrations.AlterField(
            model_name='termshift',
            name='eventDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 22, 13, 3, 42, 453229), null=True),
        ),
    ]
